feat: commit and push to dotfiles after updating Brewfile

diff --git a/dot_bashrc.tmpl b/dot_bashrc.tmpl
--- a/dot_bashrc.tmpl
+++ b/dot_bashrc.tmpl
@@ -82,8 +82,19 @@ fi
 
 {{- if eq .chezmoi.os "darwin" }}
 # Set Homebrew-file
-if [ -f $(brew --prefix)/etc/brew-wrap ]; then
+if [[ -f $(brew --prefix)/etc/brew-wrap ]]; then
 	source $(brew --prefix)/etc/brew-wrap
+
+	_post_brewfile_update() (
+		cd "$(chezmoi source-path)" || {
+			printf 'Failed to cd to %s\n' "$(chezmoi source-path)" >&2
+			return 1
+		}
+		git add .
+		read -rp 'Commit message: '
+		git commit -m "$REPLY"
+		git push origin master
+	)
 fi
 {{- end }}
 
