refactor(shell): centralize emit utility

diff --git a/home/.chezmoitemplates/utils b/home/.chezmoitemplates/utils
--- a/home/.chezmoitemplates/utils
+++ b/home/.chezmoitemplates/utils
@@ -1,14 +1,20 @@
 declare -l OS
 
 emit() {
-    case "$1" in
-        i) printf 'INFO: %s\n' "$2" >&2 ;;
-        e) printf 'ERROR: %s\n' "$2" >&2 ;;
-        w) printf 'WARNING: %s\n' "$2" >&2 ;;
-        f) printf 'FATAL: %s\n' "$2" >&2 ;;
-        *) emit e "Invalid option or format" ;;
+    local level=${1:-} message=${2:-} exit_code=${3:-}
+
+    case $level in
+        i) printf 'INFO: %s\n' "$message" >&2 ;;
+        w) printf 'WARNING: %s\n' "$message" >&2 ;;
+        e) printf 'ERROR: %s\n' "$message" >&2 ;;
+        f) printf 'FATAL: %s\n' "$message" >&2 ;;
+        *)
+            printf 'ERROR: Invalid log level: %s\n' "$level" >&2
+            return 2
+            ;;
     esac
-    [[ -z $3 ]] || exit "$3"
+
+    [[ -z $exit_code ]] || exit "$exit_code"
 }
 
 change-dir() {
